### ISSUE TITLE
Image status are not set

### ISSUE THREAD

**Issue by DOO-DEV** [arshamalh/dockeroller#8]
### Describe the bug:
The status of images doesn't set.

Beside i test a scenario when app is ruining and we create/kill a container the responsible image status doesn't change it's because the `moby` package `cli.ContainerList`  doesn't change list of containers after changes in our machine.

**Comment by arshamalh** [comment]
> The status of images doesn't set.

I guess it's quite related to the algorithm used there and also enums are not defined in a good way, I also saw your contribution to it 👍🏼

> Beside i test a scenario when app is ruining and we create/kill a container the responsible image status doesn't change it's because the moby package cli.ContainerList doesn't change list of containers after changes in our machine.

This one might be because of our wrong caching strategy, we didn't want to request the Docker daemon to list containers every time for some reason, so we cache the list of containers! and just reload it in case of container removal or /containers command.

but it seems we should change it, The containers list should also be listed after the next and prev buttons are clicked.
It should be discussed anyway.

**Comment by arshamalh** [comment]
Image status Problem fixed in #9 and 6d4eec03

Caching strategy fixed in f7e7828b
